// stdlib (C-inherited)
#include <cassert>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <cerrno>

// system (POSIX/Linux)
#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/in.h>

// C++ (Standard Library)
#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <memory>
#include <string_view>

static void msg(const std::string_view& msg) {
    std::cerr << msg << '\n';
}

static void msg_errno(const std::string_view& msg){
    std::cerr << "[errno: " << errno << "] " << msg << '\n';
}

static void die(const std::string_view& msg) {
    std::cerr << "[" << errno << "] " << msg << '\n';
    std::abort();
}

static void fd_set_nb(int fd){
    errno = 0;
    int flags = ::fcntl(fd, F_GETFL, 0);
    if(errno){
        die("fcntl error");
        return;
    }
    flags |= O_NONBLOCK;

    errno = 0;
    (void)::fcntl(fd, F_SETFL, flags);
    if(errno){
        die("fnctl error");
    }
}

constexpr size_t k_max_msg = 32 << 20; // likely largrer than kernel buffer;

struct Conn{
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    std::vector<uint8_t> incoming; // data to be parsed by the application
    std::vector<uint8_t> outgoing; // responses generated by the application
};

// append to the back
static void buf_append(std::vector<uint8_t> &buf, const uint8_t *data, size_t len){
    buf.insert(buf.end(), data, data + len);
}

// remove from the front
static void buf_consume(std::vector<uint8_t> &buf, size_t n){
    buf.erase(buf.begin(), buf.begin() + n);
}

// application callback when the listening socket is ready
static std::unique_ptr<Conn> handle_accept(int fd){
    sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);

    int connfd = ::accept(fd, reinterpret_cast<sockaddr*>(&client_addr), &addrlen);
    if(connfd < 0){
        msg_errno("accept() error");
        return nullptr;
    }

    uint32_t ip = client_addr.sin_addr.s_addr;
    std::cerr << "new client from " << (ip & 255) << "." << ((ip >> 8) & 255) << "." << ((ip >> 16) & 255) << "." << (ip >> 24) << ":" << ntohs(client_addr.sin_port) << '\n';

    // set the new connection fd to nonblocking mode
    fd_set_nb(connfd);

    //create a Conn object managed by a unique_ptr
    auto conn = std::make_unique<Conn>();
    conn->fd = connfd;
    conn->want_read = true;

    return conn;
}

constexpr size_t k_max_args = 200 * 1000;

static bool read_u32(const uint8_t *&cur, const uint8_t *end, uint32_t &out){
    if(cur + 4 > end){
        return false;
    }
    std::memcpy(&out, cur, 4);
    cur += 4;
    return true;
}

static bool read_str(const uint8_t *&cur, const uint8_t *end, size_t n, std::string &out){
    if(cur + n > end){
        return false;
    }
    out.assign(reinterpret_cast<const char*>(cur), n);
    cur += n;
    return true;
}

// +------+-----+------+-----+------+-----+-----+------+
// | nstr | len | str1 | len | str2 | ... | len | strn |
// +------+-----+------+-----+------+-----+-----+------+

static int32_t parse_req(const uint8_t *data, size_t size, std::vector<std::string> &out) {
    const uint8_t *end = data + size;
    uint32_t nstr = 0;
    
    if (!read_u32(data, end, nstr)) {
        return -1;
    }
    if (nstr > k_max_args) {
        return -1;  // safety limit
    }
    
    while (out.size() < nstr) {
        uint32_t len = 0;
        if (!read_u32(data, end, len)) {
            return -1;
        }
        
        out.emplace_back(); // safely construct a new empty string in-place
        if (!read_str(data, end, len, out.back())) {
            return -1;
        }
    }
    
    if (data != end) {
        return -1;  // trailing garbage
    }
    return 0;
}

// Response status codes
constexpr uint32_t RES_OK = 0;
constexpr uint32_t RES_ERR = 1; // error
constexpr uint32_t RES_NX = 2; // key not found


// +--------+---------+
// | status | data... |
// +--------+---------+

struct Response{
    uint32_t status = 0;
    std::vector<uint8_t> data;
};

// our in-memory Key-Value Store
static std::map<std::string, std::string> g_data;

static void do_request(std::vector<std::string> &cmd, Response &out){
    if(cmd.size() == 2 && cmd[0] == "get"){
        auto it = g_data.find(cmd[1]);
        if(it == g_data.end()){
            out.status = RES_NX; // not found
            return;
        }
        const std::string &val = it->second;
        out.data.assign(val.begin(), val.end());
    }
    else if(cmd.size() == 3 && cmd[0] == "set"){
        g_data[cmd[1]].swap(cmd[2]);
        out.status = RES_OK;
    }
    else if(cmd.size() == 2 && cmd[0] == "del"){
        g_data.erase(cmd[1]);
        out.status = RES_OK;
    }
    else{
        out.status = RES_ERR;
    }
}

static void make_response(const Response &resp, std::vector<uint8_t> &out){
    uint32_t resp_len = 4 + static_cast<uint32_t>(resp.data.size());
    buf_append(out, reinterpret_cast<const uint8_t*>(&resp_len), 4);
    buf_append(out, reinterpret_cast<const uint8_t*>(&resp.status), 4);
    buf_append(out, resp.data.data(), resp.data.size());
}

// process 1 request if there is enough data
static bool try_one_request(Conn *conn){
    // try to parse the protocol: message header
    if(conn->incoming.size() < 4){
        return false;
    }

    uint32_t len = 0;
    std::memcpy(&len, conn->incoming.data(), 4);
    if(len > k_max_msg){
        msg("too long");
        conn->want_close = true;
        return false; // want close
    }

    // message body
    if(4 + len > conn->incoming.size()){
        return false; // want read
    }

    const uint8_t *request = &conn->incoming[4];

    // got one request, try to parse the string array
    std::vector<std::string> cmd;
    if(parse_req(request, len, cmd) < 0){
        msg("bad request");
        conn->want_close = true;
        return false; // want close
    }


    Response resp;
    do_request(cmd, resp);
    make_response(resp, conn->outgoing);

    // application logic done! remove the request message.
    buf_consume(conn->incoming, 4 + len);

    return true;
}

// application callback when the socket is writable
static void handle_write(Conn *conn){
    assert(!conn->outgoing.empty());

    ssize_t rv = ::write(conn->fd, conn->outgoing.data(), conn->outgoing.size());
    if(rv < 0 && errno == EAGAIN){
        return; // actually not ready
    }

    if(rv < 0){
        msg_errno("write() error");
        conn->want_close = true; //error handling
        return;
    }

    // remove writte data from `outgoing`
    buf_consume(conn->outgoing, static_cast<size_t>(rv));

    // update the readiness intention
    if(conn->outgoing.empty()){
        conn->want_read = true;
        conn->want_write = false;
    } // else: want write
}

// application callback when the sokcet is readable
static void handle_read(Conn *conn){
    // read some data
    uint8_t buf[64 * 1024];
    ssize_t rv = ::read(conn->fd, buf, sizeof(buf));

    if(rv < 0 && errno == EAGAIN){
        return; // actually not ready
    }

    // handle IO error
    if(rv < 0){
        msg_errno("read() error");
        conn->want_close = true;
        return; // want close
    }

    // handle EOF
    if(rv == 0){
        if(conn->incoming.empty()){
        msg("client closed");
        }
        else{
            msg("unexpected EOF");
        }
        conn->want_close = true;
        return; // want close
    }

    // got some new data
    buf_append(conn->incoming, buf, static_cast<size_t>(rv));

    // parse requests and generate responses
    while(try_one_request(conn)){}

    // update the readiness intention
    if(!conn->outgoing.empty()){ // has a response
        conn->want_read = false;
        conn->want_write = true;
        // the socket is likely ready to write in a request-response protocol,
        // try to write it without waiting for the mext iteration
        return handle_write(conn);
    } // else: want read
}

int main(){

    int fd = ::socket(AF_INET, SOCK_STREAM, 0);
    if(fd < 0){
        die("socket()");
    }

    // this is needed for most server applications
    int val = 1;
    ::setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    // bind
    sockaddr_in addr = {};
    addr.sin_family = AF_INET;
    addr.sin_port = ntohs(1234);
    addr.sin_addr.s_addr = ntohl(0); // wildcard address 0.0.0.0

    int rv = ::bind(fd, reinterpret_cast<const sockaddr*>(&addr), sizeof(addr));
    if(rv){
        die("bind()");
    }

    // set the listen fd to nonblocking mode
    fd_set_nb(fd);

    // listen
    rv = ::listen(fd, SOMAXCONN);
    if(rv){
        die("listen()");
    }

    // a map of all client connections, keyed by fd
    std::vector<std::unique_ptr<Conn>> fd2conn;

    // the event loop
    std::vector<pollfd> poll_args;

    std::cout << "KV Server runnning on port 1234...\n";
    
    while(true){
        poll_args.clear();

        // put the listening socket in the first position
        pollfd pfd = {fd, POLLIN, 0};
        poll_args.push_back(pfd);

        // the rest are connection sockets
        for(const auto& conn: fd2conn){
            if(!conn){
                continue;
            }

            // always  poll() for error
            pollfd conn_pfd = {conn->fd, POLLERR, 0};

            // poll() flags from the application's intent
            if(conn->want_read){
                conn_pfd.events |= POLLIN;
            }
            if(conn->want_write){
                conn_pfd.events |= POLLOUT;
            }
            poll_args.push_back(conn_pfd);
        }

        // wait for readiness
        int poll_rv = ::poll(poll_args.data(), static_cast<nfds_t>(poll_args.size()), -1);
        if(poll_rv < 0 && errno == EINTR){
            continue; // not an error
        }
        if(poll_rv < 0){
            die("poll");
        }

        // handle the listening socket
        if(poll_args[0].revents){
            if(auto conn = handle_accept(fd)){
                // put it into the map
                if(fd2conn.size() <= static_cast<size_t>(conn->fd)){
                    fd2conn.resize(conn->fd + 1);
                }
                assert(!fd2conn[conn->fd]);
                fd2conn[conn->fd] = std::move(conn);
            }
        }

        // handle connection sockets
        for(size_t i = 1; i < poll_args.size(); ++i){ //note: skip the 1st
            uint32_t ready = poll_args[i].revents;
            if(ready == 0){
                continue;
            }

            Conn *conn = fd2conn[poll_args[i].fd].get();

            if(ready & POLLIN){
                assert(conn->want_read);
                handle_read(conn); // application logic
            }
            if(ready & POLLOUT){
                assert(conn->want_write);
                handle_write(conn); // application logic
            }

            // close the socket from socket error or application logic
            if((ready & POLLERR) || conn->want_close){
                (void)::close(conn->fd);
                // unique_ptr automatically deletes the Conn object when we set it to nullptr
                fd2conn[conn->fd] = nullptr;
            }
        }
    }

    return 0;
}